### ISSUE TITLE
function search returns(uint nextInsert)    ➡️   but we are returning value in the last line anyway

### ISSUE THREAD

**Issue by stefek99** [kleros/openiico-contract#34]
https://github.com/kleros/openiico-contract/blob/master/contracts/IICO.sol#L277-L295

**Comment by clesaege** [comment]
Yeah, what is the problem?

**Comment by stefek99** [comment]
Isn’t it a duplication?

You ether “return value”

Or have a function signature “returns something”

Similar to #28 when I didn’t know the syntax.

**Comment by clesaege** [comment]
You can also name the variable you return for better documentation.
I don't know if it actually creates it for nothing. But normally those kind of stuff are solved at the compiler level.

**Comment by stefek99** [comment]
I still don't get it.

`nextInsert` does not appear anywhere in the code, other than function signature:

![image](https://user-images.githubusercontent.com/249703/41509317-cca67738-7249-11e8-9da5-13199f3c1cc3.png)

We return `return next;` here https://github.com/kleros/openiico-contract/blob/3c57d7d6ebcd8be9fb7bae9aa4b8d22bec57603c/contracts/IICO.sol#L294

**Comment by clesaege** [comment]
Yeah, nextInsert is just the function signature, it could have been omitted from the compiler perspective but it was put there in order for readers to have better clarity about what the function returns.

**Comment by stefek99** [comment]
Let me be blatantly straight.

Because in Western culture people are so fucking polite:
- I was wondering
- if you wouldn't mind
- may I excuse you

It's OK to admit a mistake. It's OK to admit copy-paste error. It's OK to change your mind. It's OK to realize the facts came into light etc...

Wish someone told me these in my relationship.

Wish there were more strong leaders like Putin - try saying "no" to Putin LOL 😎

![image](https://user-images.githubusercontent.com/249703/41513455-a4eec862-7294-11e8-91ed-8be65c563b3e.png)

> better clarity 

**Let me be blatantly straight.**

In #28 I've learned about syntactic sugar of Solidity - nice - you can have `returns` in the function signature, so no need to `return` at the end of the function body.

So now I know the syntax, I know what it is doing, I can do the `returns` and then I don't need to `return`. This time around it's confusing (as opposed to "better clarity").

Did some reading - https://ethereum.stackexchange.com/questions/34046/what-is-the-purpose-of-giving-name-to-return-variables-in-function-declaration - they mention visual aid... 

I'll still lean towards consistency.

_(hope you still like me, 6 months ago I coudl barely follow a tutorial how to deploy a ERC20 and ICO, this time around I'm on a mission to make crypto more usable to the people)_

_(hope the IICO model will be used and reused that's why #32 so people who sent some ether will have aligned incentives to promote the project)_

`#decentralizeeverything`

**Comment by clesaege** [comment]
Yeah, as you saw on the readings, it's for visual aid to understand better what the function returns.

**Comment by stefek99** [comment]
Okay, got it.

```
browser/ballot.sol:9:9: TypeError: Different number of arguments in return statement than in returns declaration.
        return a + b;
        ^----------^
```

Sample code:
```
pragma solidity ^0.4.23;
contract ThatReturnsSomething {
    
    function Foo(uint a, uint b) public returns (uint sum) {
        sum = a + b;
    }
    
    function Bar(uint a, uint b) public {
        return a + b;
    }
    
    function Baz(uint a, uint b) public returns (uint sum) {
        return a * b; 
    }    
}
```

Ambiguity - no.
Consistency - yes.
